version: "3"

services:
  geo_service_app:
    build: .
    container_name: "geo_service_app"
    ports:
      - "8080:8080"
    depends_on:
      - geo_service_db
    networks:
      - geo_service_network

  geo_service_db:
    image: postgres:13.5-alpine
    container_name: "geo_service_db"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - PGUSER=${DB_USER}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: [ "CMD", "pg_isready -U admin" ]
      interval: 10s
      timeout: 2s
      retries: 3
    restart: unless-stopped
    networks:
      - geo_service_network

networks:
  geo_service_network:
    driver: bridge